# Generated by Django 5.1.3 on 2024-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('DateOfBirth', models.DateField(max_length=50)),
                ('Gender', models.CharField(max_length=100)),
                ('BloodGroup', models.CharField(max_length=50)),
                ('ContactNo', models.IntegerField(default=1234567890)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
    ]
